#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef SHOPLIVECOREPLAYERSDK_SWIFT_H
#define SHOPLIVECOREPLAYERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import ShopliveSDKCommon;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShopLiveCorePlayerSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK18SLLoadingIndicator")
@interface SLLoadingIndicator : SLView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK36ShopLiveBackgroundPosterImageWebView")
@interface ShopLiveBackgroundPosterImageWebView : SLView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@class WKWebView;
@class WKNavigation;

@interface ShopLiveBackgroundPosterImageWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
@end

@class NSURL;

SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK31ShopLivePlayerViewModelDelegate_")
@protocol ShopLivePlayerViewModelDelegate <NSObject>
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@class NSBundle;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK32ShopLiveBasePlayerViewController")
@interface ShopLiveBasePlayerViewController : SLViewController <ShopLivePlayerViewModelDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



@class WKFrameInfo;

@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end





@protocol UIViewControllerTransitionCoordinator;

@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK27ShopLiveBasePlayerViewModel")
@interface ShopLiveBasePlayerViewModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UITextView;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK16ShopLiveChatView")
@interface ShopLiveChatView : SLScrollView <UITextViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end

@class NSTextContainer;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveChattingView")
@interface ShopLiveChattingView : SLTextView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) BOOL hasText;
- (void)layoutSubviews;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK25ShopLiveChattingWriteView")
@interface ShopLiveChattingWriteView : SLView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didTouchSendButton;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
@end

@class UIScrollView;

@interface ShopLiveChattingWriteView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK30ShopLiveCorePlayerSDKResources")
@interface ShopLiveCorePlayerSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ShopLiveResultStatus : NSInteger;
enum ShopLiveResultAlertType : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveCouponResult")
@interface ShopLiveCouponResult : NSObject
- (nonnull instancetype)initWithCouponId:(NSString * _Nonnull)couponId success:(BOOL)success message:(NSString * _Nullable)message status:(enum ShopLiveResultStatus)status alertType:(enum ShopLiveResultAlertType)alertType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK26ShopLiveCustomActionResult")
@interface ShopLiveCustomActionResult : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id success:(BOOL)success message:(NSString * _Nullable)message status:(enum ShopLiveResultStatus)status alertType:(enum ShopLiveResultAlertType)alertType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK29ShopLiveInAppPipConfiguration")
@interface ShopLiveInAppPipConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ShopLiveInAppPipSize;
enum ShopLivePipPosition : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK30ShopLiveInAppConfigurationObjc")
@interface ShopLiveInAppConfigurationObjc : ShopLiveInAppPipConfiguration
@property (nonatomic, strong) ShopLiveInAppPipSize * _Nullable _pipSize;
@property (nonatomic) BOOL _useCloseButton;
@property (nonatomic) enum ShopLivePipPosition _pipPosition;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull _pipPinPositions;
@property (nonatomic) BOOL _enableSwipeOut;
@property (nonatomic) CGFloat _pipRadius;
- (nonnull instancetype)initWithUseCloseButton:(BOOL)useCloseButton pipPosition:(enum ShopLivePipPosition)pipPosition pipPinPosition:(NSArray<NSNumber *> * _Nonnull)pipPinPosition enableSwipeOut:(BOOL)enableSwipeOut pipSize:(ShopLiveInAppPipSize * _Nonnull)pipSize pipRadius:(CGFloat)pipRadius OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveInAppPipSize")
@interface ShopLiveInAppPipSize : NSObject
- (nonnull instancetype)initWithPipMaxSize:(CGFloat)pipMaxSize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedWidth:(CGFloat)pipFixedWidth OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedHeight:(CGFloat)pipFixedHeight OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK26ShopLiveInternalPlayerView")
@interface ShopLiveInternalPlayerView : SLView <ShopLivePlayerViewModelDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end




@interface ShopLiveInternalPlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end







@interface ShopLiveInternalPlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK23ShopLiveLastOrientation")
@interface ShopLiveLastOrientation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK11ShopLiveLog")
@interface ShopLiveLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Feature, open) {
  FeatureCLICK = 0,
  FeatureSHOW = 1,
  FeatureACTION = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveNavigationActionType, open) {
  ShopLiveNavigationActionTypePIP = 0,
  ShopLiveNavigationActionTypeKEEP = 1,
  ShopLiveNavigationActionTypeCLOSE = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveOrientation, open) {
  ShopLiveOrientationPortrait = 0,
  ShopLiveOrientationLandscape = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLivePipPosition, open) {
  ShopLivePipPositionTopLeft = 0,
  ShopLivePipPositionTopCenter = 1,
  ShopLivePipPositionTopRight = 2,
  ShopLivePipPositionMiddleLeft = 3,
  ShopLivePipPositionMiddleCenter = 4,
  ShopLivePipPositionMiddleRight = 5,
  ShopLivePipPositionBottomLeft = 6,
  ShopLivePipPositionBottomCenter = 7,
  ShopLivePipPositionBottomRight = 8,
  ShopLivePipPositionDefault = 9,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK14ShopLivePlayer")
@interface ShopLivePlayer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ShopLiveViewHiddenActionType : NSInteger;
@class UIFont;
@protocol ShopLivePlayerShareDelegate;
@class ShopLivePreviewData;
@class ShopLivePlayerData;
@class UIImage;
@class UIView;
@protocol ShopLivePlayerStateContainer;

@interface ShopLivePlayer (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
+ (void)removeParameterWithKey:(NSString * _Nonnull)key;
+ (void)addParameterWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
+ (void)setMixWithOthersWithIsMixAudio:(BOOL)isMixAudio;
+ (void)setAudioSessionCategoryWithCategory:(AVAudioSessionCategory _Nonnull)category;
+ (void)awakePlayer;
+ (void)setKeepWindowStyleOnReturnFromOsPip:(BOOL)keep;
+ (BOOL)isKeepWindowStyleOnReturnFromOsPip SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppVersion:(NSString * _Nonnull)appVersion;
+ (void)setUsingLocalStorage:(BOOL)use;
+ (BOOL)setPictureInPictureFloatingOffsetWithOffset:(UIEdgeInsets)offset SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)setPictureInPicturePaddingWithPadding:(UIEdgeInsets)padding SWIFT_WARN_UNUSED_RESULT;
+ (void)sendCommandMessageWithCommand:(NSString * _Nonnull)command payload:(NSDictionary<NSString *, id> * _Nullable)payload;
+ (void)setMuteWhenPlayStart:(BOOL)mute;
+ (void)setNextActionOnHandleNavigationWithActionType:(enum ShopLiveNavigationActionType)actionType;
+ (enum ShopLiveNavigationActionType)getNextActionTypeOnHandleNavigation SWIFT_WARN_UNUSED_RESULT;
+ (void)setEndpoint:(NSString * _Nullable)url;
+ (BOOL)isSuccessCampaignJoin SWIFT_WARN_UNUSED_RESULT;
+ (void)closeWithActionType:(enum ShopLiveViewHiddenActionType)actionType;
+ (void)setChatViewFontWithInputBoxFont:(UIFont * _Nullable)inputBoxFont sendButtonFont:(UIFont * _Nullable)sendButtonFont;
+ (void)setShareScheme:(NSString * _Nullable)scheme shareDelegate:(id <ShopLivePlayerShareDelegate> _Nullable)shareDelegate;
+ (void)hookNavigationWithNavigation:(void (^ _Nonnull)(NSURL * _Nonnull))navigation;
+ (void)onTerminated;
+ (void)setAutoResumeVideoOnCallEnded:(BOOL)autoResume;
+ (BOOL)isAutoResumeVideoOnCallEnded SWIFT_WARN_UNUSED_RESULT;
+ (void)mute;
+ (void)unmute;
+ (void)previewWithData:(ShopLivePreviewData * _Nonnull)data completion:(void (^ _Nullable)(void))completion;
+ (void)playWithData:(ShopLivePlayerData * _Nonnull)data;
+ (void)startPictureInPictureWith:(enum ShopLivePipPosition)position scale:(CGFloat)scale;
+ (void)startPictureInPicture;
+ (void)stopPictureInPicture;
+ (void)setLoadingAnimationWithImages:(NSArray<UIImage *> * _Nonnull)images;
+ (void)reloadLive;
+ (void)setEnabledPictureInPictureModeWithIsEnabled:(BOOL)isEnabled;
+ (void)setEnabledOSPictureInPictureModeWithIsEnabled:(BOOL)isEnabled;
+ (void)setInAppPipConfigurationWithConfig:(ShopLiveInAppPipConfiguration * _Nonnull)config;
+ (void)setUtmSourceWithUtmSource:(NSString * _Nullable)utmSource;
+ (void)setUtmCampaignWithUtmCampaign:(NSString * _Nullable)utmCampaign;
+ (void)setUtmMediumWithUtmMedium:(NSString * _Nullable)utmMedium;
+ (void)setUtmContentWithUtmContent:(NSString * _Nullable)utmContent;
+ (NSString * _Nullable)getUtmSource SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmCampaign SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmMedium SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmContent SWIFT_WARN_UNUSED_RESULT;
+ (void)setVisibleStatusBarWithIsVisible:(BOOL)isVisible;
+ (void)addSubViewToPreviewWithSubView:(UIView * _Nonnull)subView;
+ (CGSize)getPreviewSizeInAppPipConfiguration:(ShopLiveInAppPipConfiguration * _Nonnull)inAppPipConfiguration videoRatio:(CGSize)videoRatio SWIFT_WARN_UNUSED_RESULT;
+ (void)setResizeModeWithMode:(enum ShopLiveResizeMode)mode;
+ (void)attachHLSPlayerViewWithCompletion:(UIView * _Nonnull (^ _Nonnull)(void))completion;
+ (void)attachRTCPlayerViewWithCompletion:(UIView * _Nonnull (^ _Nonnull)(void))completion;
+ (void)attachHLSPlayerViewModelWithCompletion:(NSObject * _Nonnull (^ _Nonnull)(id <ShopLivePlayerStateContainer> _Nonnull))completion;
+ (void)attachRTCPlayerViewModelWithCompletion:(NSObject * _Nonnull (^ _Nonnull)(id <ShopLivePlayerStateContainer> _Nonnull))completion;
+ (void)forceStartWithPortraitMode:(BOOL)isForced;
@end

@class NSNotification;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK37ShopLivePlayerAudioSessionManagerImpl")
@interface ShopLivePlayerAudioSessionManagerImpl : NSObject
- (void)voiceOverStatusChanged;
- (void)handleInterruptionWithNotification:(NSNotification * _Nonnull)notification;
- (void)audioRouteChangeListenerWithNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK19ShopLivePlayerBrand")
@interface ShopLivePlayerBrand : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
- (nonnull instancetype)initWithName:(NSString * _Nullable)name identifier:(NSString * _Nullable)identifier imageUrl:(NSString * _Nullable)imageUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ShopLivePlayerCampaignStatus : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK22ShopLivePlayerCampaign")
@interface ShopLivePlayerCampaign : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic) enum ShopLivePlayerCampaignStatus campaignStatus;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title campaignStatus:(enum ShopLivePlayerCampaignStatus)campaignStatus OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ShopLivePlayerCampaignStatus, open) {
  ShopLivePlayerCampaignStatusREADY = 0,
  ShopLivePlayerCampaignStatusONAIR = 1,
  ShopLivePlayerCampaignStatusCLOSED = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK18ShopLivePlayerData")
@interface ShopLivePlayerData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK22ShopLivePlayerDataObjc")
@interface ShopLivePlayerDataObjc : ShopLivePlayerData
@property (nonatomic, copy) NSString * _Nonnull _campaignKey;
@property (nonatomic) BOOL _keepWindowStateOnPlayExecuted;
@property (nonatomic, copy) NSString * _Nonnull _referrer;
- (nonnull instancetype)initWithCampaignKey:(NSString * _Nonnull)campaignKey keepWindowStateonPlayExecuted:(BOOL)keepWindowStateonPlayExecuted referrer:(NSString * _Nonnull)referrer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK22ShopLivePlayerDelegate_")
@protocol ShopLivePlayerDelegate
- (void)handleNavigationWith:(NSURL * _Nonnull)url;
@optional
- (void)handleDownloadCouponWith:(NSString * _Nonnull)couponId result:(void (^ _Nonnull)(ShopLiveCouponResult * _Nonnull))result;
- (void)handleCustomActionWith:(NSString * _Nonnull)id type:(NSString * _Nonnull)type payload:(id _Nullable)payload result:(void (^ _Nonnull)(ShopLiveCustomActionResult * _Nonnull))result;
- (void)handleChangeCampaignStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleChangedPlayerStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
- (void)handleCampaignInfoWithCampaignInfo:(NSDictionary<NSString *, id> * _Nonnull)campaignInfo;
- (void)onSetUserName:(NSDictionary<NSString *, id> * _Nonnull)payload;
- (void)handleCommand:(NSString * _Nonnull)command with:(id _Nullable)payload;
- (void)handleReceivedCommand:(NSString * _Nonnull)command data:(NSDictionary<NSString *, id> * _Nullable)data;
- (void)playerPanGestureWithState:(enum UIGestureRecognizerState)state position:(CGPoint)position;
- (void)onEventWithName:(NSString * _Nonnull)name feature:(enum Feature)feature campaign:(NSString * _Nonnull)campaign payload:(NSDictionary<NSString *, id> * _Nonnull)payload;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK35ShopLivePlayerEventTraceManagerImpl")
@interface ShopLivePlayerEventTraceManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



typedef SWIFT_ENUM(NSInteger, ShopLivePlayerMode, open) {
  ShopLivePlayerModePlay = 0,
  ShopLivePlayerModePreview = 1,
  ShopLivePlayerModeNone = 2,
};


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK28ShopLivePlayerOverlayWebView")
@interface ShopLivePlayerOverlayWebView : SLView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@class WKUserContentController;
@class WKScriptMessage;

@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end



@class WKNavigationAction;

@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end




SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK49ShopLivePlayerOverlayWebViewNavigationManagerImpl")
@interface ShopLivePlayerOverlayWebViewNavigationManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK36ShopLivePlayerPlayControlManagerImpl")
@interface ShopLivePlayerPlayControlManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ShopLivePlayerPreviewResolution, open) {
  ShopLivePlayerPreviewResolutionLIVE = 1,
  ShopLivePlayerPreviewResolutionPREVIEW = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK27ShopLivePlayerShareCampaign")
@interface ShopLivePlayerShareCampaign : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable campaignKey;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable descriptions;
@property (nonatomic, readonly, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK23ShopLivePlayerShareData")
@interface ShopLivePlayerShareData : NSObject
@property (nonatomic, readonly, strong) ShopLivePlayerShareCampaign * _Nullable campaign;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK27ShopLivePlayerShareDelegate_")
@protocol ShopLivePlayerShareDelegate
- (void)handleShareWithData:(ShopLivePlayerShareData * _Nonnull)data;
@end

enum ShopLiveWindowStyle : NSInteger;
enum ShopLivePlayerViewProvideType : NSInteger;

/// ShopLive Campaign Public Status Interface
SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK28ShopLivePlayerStateContainer_")
@protocol ShopLivePlayerStateContainer <NSObject>
@property (nonatomic) enum ShopLiveWindowStyle windowStyle;
@property (nonatomic) BOOL isPreview;
@property (nonatomic) BOOL keepOrientationWhenPlayStart;
@property (nonatomic, copy) NSString * _Nullable shareScheme;
@property (nonatomic, strong) ShopLiveLastOrientation * _Nullable lastOrientation;
@property (nonatomic) UIDeviceOrientation prevLandscapeOrientation;
@property (nonatomic) BOOL lastPipPlaying;
@property (nonatomic) BOOL inRotating;
@property (nonatomic) BOOL screenLock;
@property (nonatomic) enum ShopLivePlayerMode playerMode;
@property (nonatomic) enum ShopLivePlayerViewProvideType viewProvideType;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK18ShopLivePlayerView")
@interface ShopLivePlayerView : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShopLivePlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <ShopLivePlayerShareDelegate>
- (void)handleShareWithData:(ShopLivePlayerShareData * _Nonnull)data;
@end







typedef SWIFT_ENUM(NSInteger, ShopLivePlayerViewProvideType, open) {
  ShopLivePlayerViewProvideTypeWindow = 0,
  ShopLivePlayerViewProvideTypeUiview = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLivePresentationStyle, open) {
  ShopLivePresentationStyleUnknown = 0,
  ShopLivePresentationStyleFullScreen = 1,
  ShopLivePresentationStylePip = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK19ShopLivePreviewData")
@interface ShopLivePreviewData : ShopLivePlayerData
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK24ShopLiveQuizSoundManager")
@interface ShopLiveQuizSoundManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveResultAlertType, open) {
  ShopLiveResultAlertTypeALERT = 0,
  ShopLiveResultAlertTypeTOAST = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveResultStatus, open) {
  ShopLiveResultStatusSHOW = 0,
  ShopLiveResultStatusHIDE = 1,
  ShopLiveResultStatusKEEP = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveStreamType, open) {
  ShopLiveStreamTypeHLS = 0,
  ShopLiveStreamTypeWEBRTC = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveVideoOrientation, open) {
  ShopLiveVideoOrientationPortrait = 0,
  ShopLiveVideoOrientationLandscape = 1,
  ShopLiveVideoOrientationUnknown = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveViewHiddenActionType, open) {
  ShopLiveViewHiddenActionTypeOnSwipeOut = 0,
  ShopLiveViewHiddenActionTypeOnBtnTapped = 1,
  ShopLiveViewHiddenActionTypeOnClose = 2,
  ShopLiveViewHiddenActionTypeOnError = 3,
  ShopLiveViewHiddenActionTypeOnRestoringPip = 4,
  ShopLiveViewHiddenActionTypeOnNavigationHandleClose = 5,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveViewTrackEvent, open) {
  ShopLiveViewTrackEventViewWillDisAppear = 0,
  ShopLiveViewTrackEventViewDidDisAppear = 1,
  ShopLiveViewTrackEventPipWillAppear = 2,
  ShopLiveViewTrackEventPipDidAppear = 3,
  ShopLiveViewTrackEventFullScreenWillAppear = 4,
  ShopLiveViewTrackEventFullScreenDidAppear = 5,
};

@class WKWebViewConfiguration;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK15ShopLiveWebView")
@interface ShopLiveWebView : SLWKWebView
@property (nonatomic, readonly, strong) SLView * _Nullable inputAccessoryView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveWindowStyle, open) {
  ShopLiveWindowStyleNone = 0,
  ShopLiveWindowStyleInAppPip = 1,
  ShopLiveWindowStyleOsPip = 2,
  ShopLiveWindowStyleNormal = 3,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK37ShoplivePlayerAppLifeCycleManagerImpl")
@interface ShoplivePlayerAppLifeCycleManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindowScene;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK14ShopliveWindow")
@interface ShopliveWindow : SLWindow
- (void)addSubview:(UIView * _Nonnull)view;
- (nonnull instancetype)initWithWindowScene:(UIWindowScene * _Nonnull)windowScene OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef SHOPLIVECOREPLAYERSDK_SWIFT_H
#define SHOPLIVECOREPLAYERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import ShopliveSDKCommon;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ShopLiveCorePlayerSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK18SLLoadingIndicator")
@interface SLLoadingIndicator : SLView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK36ShopLiveBackgroundPosterImageWebView")
@interface ShopLiveBackgroundPosterImageWebView : SLView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@class WKWebView;
@class WKNavigation;

@interface ShopLiveBackgroundPosterImageWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
@end

@class NSURL;

SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK31ShopLivePlayerViewModelDelegate_")
@protocol ShopLivePlayerViewModelDelegate <NSObject>
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end

@class NSString;
@class NSBundle;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK32ShopLiveBasePlayerViewController")
@interface ShopLiveBasePlayerViewController : SLViewController <ShopLivePlayerViewModelDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end



@class WKFrameInfo;

@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end





@protocol UIViewControllerTransitionCoordinator;

@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
@end


@interface ShopLiveBasePlayerViewController (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK27ShopLiveBasePlayerViewModel")
@interface ShopLiveBasePlayerViewModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UITextView;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK16ShopLiveChatView")
@interface ShopLiveChatView : SLScrollView <UITextViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end

@class NSTextContainer;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveChattingView")
@interface ShopLiveChattingView : SLTextView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly) BOOL hasText;
- (void)layoutSubviews;
- (BOOL)canPerformAction:(SEL _Nonnull)action withSender:(id _Nullable)sender SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK25ShopLiveChattingWriteView")
@interface ShopLiveChattingWriteView : SLView
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didTouchSendButton;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
@end

@class UIScrollView;

@interface ShopLiveChattingWriteView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK30ShopLiveCorePlayerSDKResources")
@interface ShopLiveCorePlayerSDKResources : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSBundle * _Nonnull bundle;)
+ (NSBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum ShopLiveResultStatus : NSInteger;
enum ShopLiveResultAlertType : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveCouponResult")
@interface ShopLiveCouponResult : NSObject
- (nonnull instancetype)initWithCouponId:(NSString * _Nonnull)couponId success:(BOOL)success message:(NSString * _Nullable)message status:(enum ShopLiveResultStatus)status alertType:(enum ShopLiveResultAlertType)alertType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK26ShopLiveCustomActionResult")
@interface ShopLiveCustomActionResult : NSObject
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id success:(BOOL)success message:(NSString * _Nullable)message status:(enum ShopLiveResultStatus)status alertType:(enum ShopLiveResultAlertType)alertType OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK29ShopLiveInAppPipConfiguration")
@interface ShopLiveInAppPipConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class ShopLiveInAppPipSize;
enum ShopLivePipPosition : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK30ShopLiveInAppConfigurationObjc")
@interface ShopLiveInAppConfigurationObjc : ShopLiveInAppPipConfiguration
@property (nonatomic, strong) ShopLiveInAppPipSize * _Nullable _pipSize;
@property (nonatomic) BOOL _useCloseButton;
@property (nonatomic) enum ShopLivePipPosition _pipPosition;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull _pipPinPositions;
@property (nonatomic) BOOL _enableSwipeOut;
@property (nonatomic) CGFloat _pipRadius;
- (nonnull instancetype)initWithUseCloseButton:(BOOL)useCloseButton pipPosition:(enum ShopLivePipPosition)pipPosition pipPinPosition:(NSArray<NSNumber *> * _Nonnull)pipPinPosition enableSwipeOut:(BOOL)enableSwipeOut pipSize:(ShopLiveInAppPipSize * _Nonnull)pipSize pipRadius:(CGFloat)pipRadius OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK20ShopLiveInAppPipSize")
@interface ShopLiveInAppPipSize : NSObject
- (nonnull instancetype)initWithPipMaxSize:(CGFloat)pipMaxSize OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedWidth:(CGFloat)pipFixedWidth OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithPipFixedHeight:(CGFloat)pipFixedHeight OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK26ShopLiveInternalPlayerView")
@interface ShopLiveInternalPlayerView : SLView <ShopLivePlayerViewModelDelegate>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end




@interface ShopLiveInternalPlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptTextInputPanelWithPrompt:(NSString * _Nonnull)prompt defaultText:(NSString * _Nullable)defaultText initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(NSString * _Nullable))completionHandler;
@end







@interface ShopLiveInternalPlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
- (NSURL * _Nullable)getCurrentWebViewUrl SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK23ShopLiveLastOrientation")
@interface ShopLiveLastOrientation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK11ShopLiveLog")
@interface ShopLiveLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, Feature, open) {
  FeatureCLICK = 0,
  FeatureSHOW = 1,
  FeatureACTION = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveNavigationActionType, open) {
  ShopLiveNavigationActionTypePIP = 0,
  ShopLiveNavigationActionTypeKEEP = 1,
  ShopLiveNavigationActionTypeCLOSE = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveOrientation, open) {
  ShopLiveOrientationPortrait = 0,
  ShopLiveOrientationLandscape = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLivePipPosition, open) {
  ShopLivePipPositionTopLeft = 0,
  ShopLivePipPositionTopCenter = 1,
  ShopLivePipPositionTopRight = 2,
  ShopLivePipPositionMiddleLeft = 3,
  ShopLivePipPositionMiddleCenter = 4,
  ShopLivePipPositionMiddleRight = 5,
  ShopLivePipPositionBottomLeft = 6,
  ShopLivePipPositionBottomCenter = 7,
  ShopLivePipPositionBottomRight = 8,
  ShopLivePipPositionDefault = 9,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK14ShopLivePlayer")
@interface ShopLivePlayer : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ShopLiveViewHiddenActionType : NSInteger;
@class UIFont;
@protocol ShopLivePlayerShareDelegate;
@class ShopLivePreviewData;
@class ShopLivePlayerData;
@class UIImage;
@class UIView;
@protocol ShopLivePlayerStateContainer;

@interface ShopLivePlayer (SWIFT_EXTENSION(ShopLiveCorePlayerSDK))
+ (void)removeParameterWithKey:(NSString * _Nonnull)key;
+ (void)addParameterWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
+ (void)setMixWithOthersWithIsMixAudio:(BOOL)isMixAudio;
+ (void)setAudioSessionCategoryWithCategory:(AVAudioSessionCategory _Nonnull)category;
+ (void)awakePlayer;
+ (void)setKeepWindowStyleOnReturnFromOsPip:(BOOL)keep;
+ (BOOL)isKeepWindowStyleOnReturnFromOsPip SWIFT_WARN_UNUSED_RESULT;
+ (void)setAppVersion:(NSString * _Nonnull)appVersion;
+ (void)setUsingLocalStorage:(BOOL)use;
+ (BOOL)setPictureInPictureFloatingOffsetWithOffset:(UIEdgeInsets)offset SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)setPictureInPicturePaddingWithPadding:(UIEdgeInsets)padding SWIFT_WARN_UNUSED_RESULT;
+ (void)sendCommandMessageWithCommand:(NSString * _Nonnull)command payload:(NSDictionary<NSString *, id> * _Nullable)payload;
+ (void)setMuteWhenPlayStart:(BOOL)mute;
+ (void)setNextActionOnHandleNavigationWithActionType:(enum ShopLiveNavigationActionType)actionType;
+ (enum ShopLiveNavigationActionType)getNextActionTypeOnHandleNavigation SWIFT_WARN_UNUSED_RESULT;
+ (void)setEndpoint:(NSString * _Nullable)url;
+ (BOOL)isSuccessCampaignJoin SWIFT_WARN_UNUSED_RESULT;
+ (void)closeWithActionType:(enum ShopLiveViewHiddenActionType)actionType;
+ (void)setChatViewFontWithInputBoxFont:(UIFont * _Nullable)inputBoxFont sendButtonFont:(UIFont * _Nullable)sendButtonFont;
+ (void)setShareScheme:(NSString * _Nullable)scheme shareDelegate:(id <ShopLivePlayerShareDelegate> _Nullable)shareDelegate;
+ (void)hookNavigationWithNavigation:(void (^ _Nonnull)(NSURL * _Nonnull))navigation;
+ (void)onTerminated;
+ (void)setAutoResumeVideoOnCallEnded:(BOOL)autoResume;
+ (BOOL)isAutoResumeVideoOnCallEnded SWIFT_WARN_UNUSED_RESULT;
+ (void)mute;
+ (void)unmute;
+ (void)previewWithData:(ShopLivePreviewData * _Nonnull)data completion:(void (^ _Nullable)(void))completion;
+ (void)playWithData:(ShopLivePlayerData * _Nonnull)data;
+ (void)startPictureInPictureWith:(enum ShopLivePipPosition)position scale:(CGFloat)scale;
+ (void)startPictureInPicture;
+ (void)stopPictureInPicture;
+ (void)setLoadingAnimationWithImages:(NSArray<UIImage *> * _Nonnull)images;
+ (void)reloadLive;
+ (void)setEnabledPictureInPictureModeWithIsEnabled:(BOOL)isEnabled;
+ (void)setEnabledOSPictureInPictureModeWithIsEnabled:(BOOL)isEnabled;
+ (void)setInAppPipConfigurationWithConfig:(ShopLiveInAppPipConfiguration * _Nonnull)config;
+ (void)setUtmSourceWithUtmSource:(NSString * _Nullable)utmSource;
+ (void)setUtmCampaignWithUtmCampaign:(NSString * _Nullable)utmCampaign;
+ (void)setUtmMediumWithUtmMedium:(NSString * _Nullable)utmMedium;
+ (void)setUtmContentWithUtmContent:(NSString * _Nullable)utmContent;
+ (NSString * _Nullable)getUtmSource SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmCampaign SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmMedium SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nullable)getUtmContent SWIFT_WARN_UNUSED_RESULT;
+ (void)setVisibleStatusBarWithIsVisible:(BOOL)isVisible;
+ (void)addSubViewToPreviewWithSubView:(UIView * _Nonnull)subView;
+ (CGSize)getPreviewSizeInAppPipConfiguration:(ShopLiveInAppPipConfiguration * _Nonnull)inAppPipConfiguration videoRatio:(CGSize)videoRatio SWIFT_WARN_UNUSED_RESULT;
+ (void)setResizeModeWithMode:(enum ShopLiveResizeMode)mode;
+ (void)attachHLSPlayerViewWithCompletion:(UIView * _Nonnull (^ _Nonnull)(void))completion;
+ (void)attachRTCPlayerViewWithCompletion:(UIView * _Nonnull (^ _Nonnull)(void))completion;
+ (void)attachHLSPlayerViewModelWithCompletion:(NSObject * _Nonnull (^ _Nonnull)(id <ShopLivePlayerStateContainer> _Nonnull))completion;
+ (void)attachRTCPlayerViewModelWithCompletion:(NSObject * _Nonnull (^ _Nonnull)(id <ShopLivePlayerStateContainer> _Nonnull))completion;
+ (void)forceStartWithPortraitMode:(BOOL)isForced;
@end

@class NSNotification;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK37ShopLivePlayerAudioSessionManagerImpl")
@interface ShopLivePlayerAudioSessionManagerImpl : NSObject
- (void)voiceOverStatusChanged;
- (void)handleInterruptionWithNotification:(NSNotification * _Nonnull)notification;
- (void)audioRouteChangeListenerWithNotification:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK19ShopLivePlayerBrand")
@interface ShopLivePlayerBrand : NSObject
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable imageUrl;
- (nonnull instancetype)initWithName:(NSString * _Nullable)name identifier:(NSString * _Nullable)identifier imageUrl:(NSString * _Nullable)imageUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum ShopLivePlayerCampaignStatus : NSInteger;

SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK22ShopLivePlayerCampaign")
@interface ShopLivePlayerCampaign : NSObject
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic) enum ShopLivePlayerCampaignStatus campaignStatus;
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title campaignStatus:(enum ShopLivePlayerCampaignStatus)campaignStatus OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ShopLivePlayerCampaignStatus, open) {
  ShopLivePlayerCampaignStatusREADY = 0,
  ShopLivePlayerCampaignStatusONAIR = 1,
  ShopLivePlayerCampaignStatusCLOSED = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK18ShopLivePlayerData")
@interface ShopLivePlayerData : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK22ShopLivePlayerDataObjc")
@interface ShopLivePlayerDataObjc : ShopLivePlayerData
@property (nonatomic, copy) NSString * _Nonnull _campaignKey;
@property (nonatomic) BOOL _keepWindowStateOnPlayExecuted;
@property (nonatomic, copy) NSString * _Nonnull _referrer;
- (nonnull instancetype)initWithCampaignKey:(NSString * _Nonnull)campaignKey keepWindowStateonPlayExecuted:(BOOL)keepWindowStateonPlayExecuted referrer:(NSString * _Nonnull)referrer OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK22ShopLivePlayerDelegate_")
@protocol ShopLivePlayerDelegate
- (void)handleNavigationWith:(NSURL * _Nonnull)url;
@optional
- (void)handleDownloadCouponWith:(NSString * _Nonnull)couponId result:(void (^ _Nonnull)(ShopLiveCouponResult * _Nonnull))result;
- (void)handleCustomActionWith:(NSString * _Nonnull)id type:(NSString * _Nonnull)type payload:(id _Nullable)payload result:(void (^ _Nonnull)(ShopLiveCustomActionResult * _Nonnull))result;
- (void)handleChangeCampaignStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleChangedPlayerStatusWithStatus:(NSString * _Nonnull)status;
- (void)handleErrorWithCode:(NSString * _Nonnull)code message:(NSString * _Nonnull)message;
- (void)handleCampaignInfoWithCampaignInfo:(NSDictionary<NSString *, id> * _Nonnull)campaignInfo;
- (void)onSetUserName:(NSDictionary<NSString *, id> * _Nonnull)payload;
- (void)handleCommand:(NSString * _Nonnull)command with:(id _Nullable)payload;
- (void)handleReceivedCommand:(NSString * _Nonnull)command data:(NSDictionary<NSString *, id> * _Nullable)data;
- (void)playerPanGestureWithState:(enum UIGestureRecognizerState)state position:(CGPoint)position;
- (void)onEventWithName:(NSString * _Nonnull)name feature:(enum Feature)feature campaign:(NSString * _Nonnull)campaign payload:(NSDictionary<NSString *, id> * _Nonnull)payload;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK35ShopLivePlayerEventTraceManagerImpl")
@interface ShopLivePlayerEventTraceManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



typedef SWIFT_ENUM(NSInteger, ShopLivePlayerMode, open) {
  ShopLivePlayerModePlay = 0,
  ShopLivePlayerModePreview = 1,
  ShopLivePlayerModeNone = 2,
};


SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK28ShopLivePlayerOverlayWebView")
@interface ShopLivePlayerOverlayWebView : SLView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@class WKUserContentController;
@class WKScriptMessage;

@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end


@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <UIScrollViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end



@class WKNavigationAction;

@interface ShopLivePlayerOverlayWebView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didCommitNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
@end




SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK49ShopLivePlayerOverlayWebViewNavigationManagerImpl")
@interface ShopLivePlayerOverlayWebViewNavigationManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK36ShopLivePlayerPlayControlManagerImpl")
@interface ShopLivePlayerPlayControlManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ShopLivePlayerPreviewResolution, open) {
  ShopLivePlayerPreviewResolutionLIVE = 1,
  ShopLivePlayerPreviewResolutionPREVIEW = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK27ShopLivePlayerShareCampaign")
@interface ShopLivePlayerShareCampaign : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable campaignKey;
@property (nonatomic, readonly, copy) NSString * _Nullable title;
@property (nonatomic, readonly, copy) NSString * _Nullable descriptions;
@property (nonatomic, readonly, copy) NSString * _Nullable thumbnail;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK23ShopLivePlayerShareData")
@interface ShopLivePlayerShareData : NSObject
@property (nonatomic, readonly, strong) ShopLivePlayerShareCampaign * _Nullable campaign;
@property (nonatomic, readonly, copy) NSString * _Nullable url;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK27ShopLivePlayerShareDelegate_")
@protocol ShopLivePlayerShareDelegate
- (void)handleShareWithData:(ShopLivePlayerShareData * _Nonnull)data;
@end

enum ShopLiveWindowStyle : NSInteger;
enum ShopLivePlayerViewProvideType : NSInteger;

/// ShopLive Campaign Public Status Interface
SWIFT_PROTOCOL("_TtP21ShopLiveCorePlayerSDK28ShopLivePlayerStateContainer_")
@protocol ShopLivePlayerStateContainer <NSObject>
@property (nonatomic) enum ShopLiveWindowStyle windowStyle;
@property (nonatomic) BOOL isPreview;
@property (nonatomic) BOOL keepOrientationWhenPlayStart;
@property (nonatomic, copy) NSString * _Nullable shareScheme;
@property (nonatomic, strong) ShopLiveLastOrientation * _Nullable lastOrientation;
@property (nonatomic) UIDeviceOrientation prevLandscapeOrientation;
@property (nonatomic) BOOL lastPipPlaying;
@property (nonatomic) BOOL inRotating;
@property (nonatomic) BOOL screenLock;
@property (nonatomic) enum ShopLivePlayerMode playerMode;
@property (nonatomic) enum ShopLivePlayerViewProvideType viewProvideType;
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK18ShopLivePlayerView")
@interface ShopLivePlayerView : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface ShopLivePlayerView (SWIFT_EXTENSION(ShopLiveCorePlayerSDK)) <ShopLivePlayerShareDelegate>
- (void)handleShareWithData:(ShopLivePlayerShareData * _Nonnull)data;
@end







typedef SWIFT_ENUM(NSInteger, ShopLivePlayerViewProvideType, open) {
  ShopLivePlayerViewProvideTypeWindow = 0,
  ShopLivePlayerViewProvideTypeUiview = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLivePresentationStyle, open) {
  ShopLivePresentationStyleUnknown = 0,
  ShopLivePresentationStyleFullScreen = 1,
  ShopLivePresentationStylePip = 2,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK19ShopLivePreviewData")
@interface ShopLivePreviewData : ShopLivePlayerData
@end


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK24ShopLiveQuizSoundManager")
@interface ShopLiveQuizSoundManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveResultAlertType, open) {
  ShopLiveResultAlertTypeALERT = 0,
  ShopLiveResultAlertTypeTOAST = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveResultStatus, open) {
  ShopLiveResultStatusSHOW = 0,
  ShopLiveResultStatusHIDE = 1,
  ShopLiveResultStatusKEEP = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveStreamType, open) {
  ShopLiveStreamTypeHLS = 0,
  ShopLiveStreamTypeWEBRTC = 1,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveVideoOrientation, open) {
  ShopLiveVideoOrientationPortrait = 0,
  ShopLiveVideoOrientationLandscape = 1,
  ShopLiveVideoOrientationUnknown = 2,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveViewHiddenActionType, open) {
  ShopLiveViewHiddenActionTypeOnSwipeOut = 0,
  ShopLiveViewHiddenActionTypeOnBtnTapped = 1,
  ShopLiveViewHiddenActionTypeOnClose = 2,
  ShopLiveViewHiddenActionTypeOnError = 3,
  ShopLiveViewHiddenActionTypeOnRestoringPip = 4,
  ShopLiveViewHiddenActionTypeOnNavigationHandleClose = 5,
};

typedef SWIFT_ENUM(NSInteger, ShopLiveViewTrackEvent, open) {
  ShopLiveViewTrackEventViewWillDisAppear = 0,
  ShopLiveViewTrackEventViewDidDisAppear = 1,
  ShopLiveViewTrackEventPipWillAppear = 2,
  ShopLiveViewTrackEventPipDidAppear = 3,
  ShopLiveViewTrackEventFullScreenWillAppear = 4,
  ShopLiveViewTrackEventFullScreenDidAppear = 5,
};

@class WKWebViewConfiguration;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK15ShopLiveWebView")
@interface ShopLiveWebView : SLWKWebView
@property (nonatomic, readonly, strong) SLView * _Nullable inputAccessoryView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration * _Nonnull)configuration OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ShopLiveWindowStyle, open) {
  ShopLiveWindowStyleNone = 0,
  ShopLiveWindowStyleInAppPip = 1,
  ShopLiveWindowStyleOsPip = 2,
  ShopLiveWindowStyleNormal = 3,
};


SWIFT_CLASS("_TtC21ShopLiveCorePlayerSDK37ShoplivePlayerAppLifeCycleManagerImpl")
@interface ShoplivePlayerAppLifeCycleManagerImpl : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindowScene;

SWIFT_RESILIENT_CLASS("_TtC21ShopLiveCorePlayerSDK14ShopliveWindow")
@interface ShopliveWindow : SLWindow
- (void)addSubview:(UIView * _Nonnull)view;
- (nonnull instancetype)initWithWindowScene:(UIWindowScene * _Nonnull)windowScene OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
